### ISSUE TITLE
Consider providing OPAM package

### ISSUE THREAD

**Issue by darioteixeira** [johnelse/ocaml-osc#8]
These days not being available on OPAM is almost like not existing... :-)

**Comment by johnelse** [comment]
I totally agree :)

Don't think this is really ready for upstreaming yet though - it needs bundle support at least!

For now I have a package tracking the master branch here: https://github.com/johnelse/opam-repo-johnelse/tree/master/packages/osc/osc.0.1.0

**Comment by johnelse** [comment]
opam package on the way...https://github.com/ocaml/opam-repository/pull/5322
